In [1]:
import torch

In [2]:
torch.__version__

'2.7.1'

In [3]:
x = torch.empty(4,2)

In [4]:
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [18]:
#Creates a tensor of shape 4 rows and 2 columns
x = torch.rand(4,2) 

In [6]:
print(x)

tensor([[0.3703, 0.4983],
        [0.7660, 0.1793],
        [0.0576, 0.5275],
        [0.0434, 0.1663]])


In [19]:
#Creates a tensor with 4 rows and 2 columns.
#All elements in this tensor are initialized to 0
#the data type is integer (long)

x= torch.zeros(4,2, dtype=torch.long)

In [8]:
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [9]:
x =torch.tensor([3,2.3])

In [10]:
print(x)

tensor([3.0000, 2.3000])


In [20]:
#Creates a 2x4 tensor of ones with double precision, matching the device of the original tensor x

x = x.new_ones(2,4, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [21]:
#replaces x with a tensor of the same shape filled with random values drawn from a standard normal distribution.
x = torch.randn_like(x, dtype=torch.float)

In [22]:
print(x)

tensor([[ 0.0454, -0.3566,  0.8172, -0.6865],
        [ 0.4136, -0.6114, -0.6122,  1.0139]])
