In [1]:
import pandas as pd

In [4]:
#series = 1차원 배열
sr = pd.Series([17000, 18000, 1000, 5000],
               index=["pizza", "chicken", "cola", "beer"])
print('series output :')
print('-'*15)
print(sr)

series output :
---------------
pizza      17000
chicken    18000
cola        1000
beer        5000
dtype: int64


In [3]:
print('value of series : {}'.format(sr.values))
print('index: {}'.format(sr.index))

value of series : [17000 18000  1000  5000]
index: Index(['pizza', 'chicken', 'cola', 'beer'], dtype='object')


In [5]:
#dataframe = 2 차원 리스트
values = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
index = ['one', 'two', 'three']
columns = ['A', 'B', 'C']

df = pd.DataFrame(values, index=index, columns=columns)

print('dataframe output :')
print('-'*18)
print(df)

dataframe output :
------------------
       A  B  C
one    1  2  3
two    4  5  6
three  7  8  9


In [6]:
print('Dataframe index : {}'.format(df.index))
print('Dataframe columns: {}'.format(df.columns))
print('Dataframe value :')
print('-'*18)
print(df.values)

Dataframe index : Index(['one', 'two', 'three'], dtype='object')
Dataframe columns: Index(['A', 'B', 'C'], dtype='object')
Dataframe value :
------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:

data = [
    ['1000', 'Steve', 90.72], 
    ['1001', 'James', 78.09], 
    ['1002', 'Doyeon', 98.43], 
    ['1003', 'Jane', 64.19], 
    ['1004', 'Pilwoong', 81.30],
    ['1005', 'Tony', 99.14],
]

df = pd.DataFrame(data)
print(df)


      0         1      2
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14


In [9]:
df = pd.DataFrame(data, columns=['id', 'name', 'score'])
print(df)

     id      name  score
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14


In [10]:
print(df.head(3))

     id    name  score
0  1000   Steve  90.72
1  1001   James  78.09
2  1002  Doyeon  98.43


In [11]:
# '학번'에 해당되는 열을 보기
print(df['id'])


0    1000
1    1001
2    1002
3    1003
4    1004
5    1005
Name: id, dtype: object


In [12]:
import numpy as np

In [13]:
vec = np.array([1, 2, 3, 4, 5])
print(vec)

[1 2 3 4 5]


In [14]:
mat = np.array([[10, 20, 30], [ 60, 70, 80]]) 
print(mat)

[[10 20 30]
 [60 70 80]]


In [15]:
print('vec의 타입 :',type(vec))
print('mat의 타입 :',type(mat))

vec의 타입 : <class 'numpy.ndarray'>
mat의 타입 : <class 'numpy.ndarray'>


In [16]:
print('vec의 축의 개수 :',vec.ndim) # 축의 개수 출력
print('vec의 크기(shape) :',vec.shape) # 크기 출력

vec의 축의 개수 : 1
vec의 크기(shape) : (5,)


In [17]:
# 모든 값이 0인 2x3 배열 생성.
zero_mat = np.zeros((2,3))
print(zero_mat)

[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
one_mat = np.ones((2,3))
print(one_mat)


[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
same_value_mat = np.full((2,2), 7)
print(same_value_mat)

[[7 7]
 [7 7]]


In [21]:
#a 3×3 identity matrix 
#a square matrix with 1's on the diagonal 
eye_mat = np.eye(3)
print(eye_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
random_mat = np.random.random((2,2)) # 임의의 값으로 채워진 배열 생성
print(random_mat)

[[0.15922279 0.76521034]
 [0.34504965 0.58818135]]


In [23]:
# 0부터 9까지
range_vec = np.arange(10)
print(range_vec)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
# 1부터 9까지 +2씩 적용되는 범위
#starts from 1, stops before 10, increments by 2
n = 2
range_n_step_vec = np.arange(1, 10, n)
print(range_n_step_vec)

[1 3 5 7 9]


In [26]:
reshape_mat = np.array(np.arange(30)).reshape((5,6))
print(reshape_mat)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [27]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [28]:
#slicing
slicing_mat = mat[0, :]
print(slicing_mat)

[1 2 3]


In [29]:
slicing_mat = mat[:, 1]
print(slicing_mat)

[2 5]


In [31]:
#integer indexing

In [32]:
mat = np.array([[1, 2], [4, 5], [7, 8]])
print(mat)

[[1 2]
 [4 5]
 [7 8]]


In [33]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [34]:
result = x + y
print(result)


[5 7 9]


In [35]:
result = x - y
print(result)

[-3 -3 -3]


In [36]:
result = result * x
print(result)

[-3 -6 -9]


In [37]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])
mat3 = np.dot(mat1, mat2)
print(mat3)

[[19 22]
 [43 50]]
