In [17]:
import torch

In [2]:
ft = torch.FloatTensor([1,2,3])
print(ft)

tensor([1., 2., 3.])


In [3]:
print(ft.dtype)

torch.float32


In [18]:
# Convert to int16 using .short()
print(ft.short())

tensor([1, 2, 3], dtype=torch.int16)


In [19]:
#Convert into long
print(ft.long())

tensor([1, 2, 3])


In [20]:
print(ft.int())

tensor([1, 2, 3], dtype=torch.int32)


In [21]:
it = torch.IntTensor([1, 2, 3])
print(it)

tensor([1, 2, 3], dtype=torch.int32)


In [22]:
it = torch.tensor([1, 2, 3], dtype=torch.int32)  # 또는 int64
print(it)

tensor([1, 2, 3], dtype=torch.int32)


In [23]:
print(it.float())

tensor([1., 2., 3.])


In [24]:
print(it.double())

tensor([1., 2., 3.], dtype=torch.float64)


In [12]:
print(it.half())

tensor([1., 2., 3.], dtype=torch.float16)


In [13]:
#CUDA Tensors

In [25]:
x = torch.randn(1)
print(x)

tensor([0.2467])


In [27]:
print(x.item())

0.24669529497623444


In [29]:
print(x.dtype)

torch.float32


In [39]:
#It checks:
#If a CUDA-compatible GPU is available, use 'cuda'.
#Otherwise, use 'cpu'.
#MPS :MPS(Metal Performance Shaders)

device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
print(f"Using device: {device}")

Using device: mps


In [40]:
print(device)

mps


In [47]:
#creates a new tensor y that has the same shape as x, filled entirely with ones, and places it on the specified device (e.g., "mps" for Apple)
y = torch.ones_like (x, device = device)

In [48]:
print(y)

#output breakdown 
#tensor([1.]) → A 1-dimensional tensor containing the value 1.0
#y is a tensor containing a single value 1.0 and it is located on the MPS GPU backend.

tensor([1.], device='mps:0')


In [49]:
#moves the tensor x to the specified computation device.
x = x.to(device)

In [44]:
print(x)

tensor([0.2467], device='mps:0')


In [45]:
z = x+y

In [46]:
print(z)

tensor([1.2467], device='mps:0')


In [53]:
print(z.dtype)

torch.float32


In [ ]:
#scalar

In [55]:
t0 = torch.tensor(0)

In [56]:
print(t0)

tensor(0)


In [57]:
print(t0.ndim)

0


In [58]:
print(t0.shape)

torch.Size([])


In [59]:
#1D Tensor (Vector)

In [60]:
t1 = torch.tensor([1,2,3])

In [61]:
print(t1)

tensor([1, 2, 3])


In [62]:
print(t1.ndim)

1


In [63]:
print(t1.shape)

torch.Size([3])


In [64]:
#2D Tensor (Matrix)

In [66]:
t2 = torch.tensor([[1,2,3],[4,5,6], [7,8,9]])

In [67]:
print(t2)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [68]:
print(t2.ndim)

2


In [76]:
print(t2.shape)

torch.Size([12, 3])


In [77]:
#3D tensor -timestamps, features, samples

In [85]:
t3 = torch.tensor([
  [  # 첫 번째 층 (2차원 배열)
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
  ],
  [  # 두 번째 층
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
  ]
])

In [86]:
print(t3)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [87]:
print(t3.ndim)

3


In [ ]:
#4D tensor 