In [1]:
import torch

In [2]:
x = torch.zeros(4,2, dtype=torch.long)

In [3]:
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [4]:
x = torch.tensor([3,2,3])

In [5]:
print(x)

tensor([3, 2, 3])


In [6]:
x = x.new_ones(2,4, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [7]:
#creates a new tensor with the same shape and data type as the tensor x.
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.7665, -0.9704, -0.6103, -1.7214],
        [ 0.8021,  0.3413, -0.3718,  0.4418]])


In [8]:
#calculating tensor size

In [9]:
print(x.size())

torch.Size([2, 4])


In [10]:
ft = torch.tensor([1, 2, 3], dtype=torch.float32)
print(ft)

tensor([1., 2., 3.])


In [11]:
print(ft.dtype)

torch.float32


In [16]:
#data type casting

print(ft.short())
print(ft.int())
print(ft.long())


tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [17]:
it = torch.IntTensor([1, 2, 3])
print(it)
print(it.type)

tensor([1, 2, 3], dtype=torch.int32)
<built-in method type of Tensor object at 0x11736b9b0>


In [18]:
it = torch.tensor([1, 2, 3], dtype=torch.int32)
print(it.float())
print(it.double())
print(it.to(dtype=torch.float16))  # half() 대신 to() 사용


tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)


In [19]:
ft = torch.tensor([1, 2, 3], dtype=torch.float32)
print(ft.double())
print(ft.half())

tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)


In [ ]:
#Cuda Tensor

In [21]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-0.6152])
-0.6151987314224243
torch.float32


In [24]:
#sets the device (CPU or GPU) for PyTorch tensor operations.
#device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [34]:
#print(torch.cuda.is_available())  

In [35]:
import torch
print(torch.backends.mps.is_available())  # Mac에서 Metal(MPS) 지원 여부


True


In [36]:
!pip install torch torchvision torchaudio

In [29]:
import torch

if torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")


In [37]:
print(device)

mps


In [31]:
y = torch.ones_like(x, device=device)
print(y)

tensor([1.], device='mps:0')


In [33]:
x = x.to(device)
print(x)
z = x+y

tensor([-0.6152], device='mps:0')


In [43]:
z_cpu = z.to('cpu').float()
print(z_cpu)            # shows the tensor values
print(z_cpu.device)     #confirms the device is CPU
print(z_cpu.dtype)      # confirms the data type is float32

tensor([0.3848])
cpu
torch.float32


In [44]:
#0D/Scalar 

In [45]:
t0 = torch.tensor(0)

In [46]:
print(t0.dim)
print(t0.shape)
print(t0)

<built-in method dim of Tensor object at 0x117788770>
torch.Size([])
tensor(0)


In [47]:
#1D/tensor  

In [48]:
t1 = torch.tensor([1,2,3])

In [49]:
print(t1.dim)
print(t1.shape)
print(t1)

<built-in method dim of Tensor object at 0x1224efe90>
torch.Size([3])
tensor([1, 2, 3])


In [54]:
#2D/tensor (Matrix) 

In [55]:
t2 = torch.tensor([[1,2,3],
                 [4,5,6], 
                 [7,8,9]])

In [56]:
print(t2.dim)
print(t2.shape)
print(t2)

<built-in method dim of Tensor object at 0x122508590>
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [57]:
 #3D/tensor (structure-samples, timestamps, feature) 

In [58]:
t3 = torch.tensor([
    [1, 2, 3],
    [4, 5, 6], 
    [7, 8, 9],
    [1, 2, 3],
    [4, 5, 6], 
    [7, 8, 9],
    [1, 2, 3],
    [4, 5, 6], 
    [7, 8, 9]
])

In [59]:
print(t3.dim)
print(t3.shape)
print(t3)

<built-in method dim of Tensor object at 0x1224ef770>
torch.Size([9, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [61]:
#tensor operation

In [62]:
import math

In [63]:
a = torch.rand(1,2) *2-1

In [68]:
print(a)

tensor([-1.5000,  2.3000, -3.7000])


In [69]:
a = torch.tensor([-1.5, 2.3, -3.7])
print(torch.abs(a))     # Absolute value
print(torch.ceil(a))    # # Ceiling function
print(a.float())  # Data type conversion
print(torch.clamp(a, -0.5, 0.5)) # Clamp values

tensor([1.5000, 2.3000, 3.7000])
tensor([-1.,  3., -3.])
tensor([-1.5000,  2.3000, -3.7000])
tensor([-0.5000,  0.5000, -0.5000])


In [75]:
print(torch.min(a))    # min value
print(torch.max(a))    # max value 
print(torch.mean(a))   # average value
print(torch.std(a))   #standard deviation
print(torch.prod(a))   #Returns the product of all tensor elements
print(torch.unique(torch.tensor([1,2,3,1,2,2])))  #print(torch.prod(a))   #Returns the product of all tensor elements


tensor(-3.7000)
tensor(2.3000)
tensor(-0.9667)
tensor(3.0353)
tensor(12.7650)
tensor([1, 2, 3])


In [76]:
#argmax&argmin

In [78]:
#argmax

In [79]:
x = torch.rand(2,2)
print(x)
print(x.max(dim=0))
print(x.max(dim=1))


tensor([[0.6946, 0.3503],
        [0.7688, 0.1633]])
torch.return_types.max(
values=tensor([0.7688, 0.3503]),
indices=tensor([1, 0]))
torch.return_types.max(
values=tensor([0.6946, 0.7688]),
indices=tensor([0, 0]))


In [80]:
x = torch.rand(2,2)
print(x)
print(x.min(dim=0))
print(x.min(dim=1))


tensor([[0.0200, 0.3228],
        [0.8956, 0.3089]])
torch.return_types.min(
values=tensor([0.0200, 0.3089]),
indices=tensor([0, 1]))
torch.return_types.min(
values=tensor([0.0200, 0.3089]),
indices=tensor([0, 1]))


In [81]:
x = torch.rand(2,2)
print(x)
y=torch.rand(2,2)
print(y)

tensor([[0.3210, 0.4612],
        [0.6814, 0.3946]])
tensor([[0.7723, 0.4227],
        [0.1605, 0.8055]])


In [82]:
print(x+y)

tensor([[1.0934, 0.8839],
        [0.8420, 1.2001]])


In [83]:
print(torch.add(x,y))

tensor([[1.0934, 0.8839],
        [0.8420, 1.2001]])


In [85]:
result= torch.empty(2,4)
torch.add(x,y, out=result)
print(result)

tensor([[1.0934, 0.8839],
        [0.8420, 1.2001]])


/var/folders/6y/xtl4b0cx1cs9zrr9n5y814_h0000gn/T/ipykernel_13888/1621708138.py:2: UserWarning: An output with one or more elements was resized since it had shape [2, 4], which does not match the required output shape [2, 2]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/Resize.cpp:37.)
  torch.add(x,y, out=result)


In [86]:
#in-place

In [88]:
print(x)
print(y)
y.add_(x) #return y=x+y
print(y)

tensor([[0.3210, 0.4612],
        [0.6814, 0.3946]])
tensor([[1.0934, 0.8839],
        [0.8420, 1.2001]])
tensor([[1.4144, 1.3451],
        [1.5234, 1.5947]])


In [89]:
#substraction

In [91]:
print(x)
print(y)
print(x-y)
print(torch.sub(x,y))
print(x.sub(y))

tensor([[0.3210, 0.4612],
        [0.6814, 0.3946]])
tensor([[1.4144, 1.3451],
        [1.5234, 1.5947]])
tensor([[-1.0934, -0.8839],
        [-0.8420, -1.2001]])
tensor([[-1.0934, -0.8839],
        [-0.8420, -1.2001]])
tensor([[-1.0934, -0.8839],
        [-0.8420, -1.2001]])


In [92]:
#multiplication

In [95]:
print(x)
print(y)
print(x * y)
print(torch.mul(x,y))
print(x.mul(y))

tensor([[0.3210, 0.4612],
        [0.6814, 0.3946]])
tensor([[1.4144, 1.3451],
        [1.5234, 1.5947]])
tensor([[0.4541, 0.6203],
        [1.0381, 0.6292]])
tensor([[0.4541, 0.6203],
        [1.0381, 0.6292]])
tensor([[0.4541, 0.6203],
        [1.0381, 0.6292]])


In [94]:
#division

In [96]:
print(x)
print(y)
print(x / y)
print(torch.div(x,y))
print(x.div(y))

tensor([[0.3210, 0.4612],
        [0.6814, 0.3946]])
tensor([[1.4144, 1.3451],
        [1.5234, 1.5947]])
tensor([[0.2270, 0.3429],
        [0.4473, 0.2474]])
tensor([[0.2270, 0.3429],
        [0.4473, 0.2474]])
tensor([[0.2270, 0.3429],
        [0.4473, 0.2474]])


In [97]:
#dot product

In [98]:
print(x)
print(y)
print(torch.matmul(x,y))
z = torch.mm(x,y)
print(z)

tensor([[0.3210, 0.4612],
        [0.6814, 0.3946]])
tensor([[1.4144, 1.3451],
        [1.5234, 1.5947]])
tensor([[1.1567, 1.1673],
        [1.5650, 1.5459]])
tensor([[1.1567, 1.1673],
        [1.5650, 1.5459]])


In [99]:
#SVD

In [100]:
print(torch.svd(z))

torch.return_types.svd(
U=tensor([[-0.5985, -0.8011],
        [-0.8011,  0.5985]]),
S=tensor([2.7457, 0.0141]),
V=tensor([[-0.7087,  0.7055],
        [-0.7055, -0.7087]]))


In [102]:
#Manipulation

In [105]:
x = torch.tensor ([[1,2],[3,4]])
print(x)

tensor([[1, 2],
        [3, 4]])


In [106]:
print(x[0,0])
print(x[0,1])
print(x[1,0])
print(x[1,1])

tensor(1)
tensor(2)
tensor(3)
tensor(4)


In [107]:
#slicing

In [108]:
print(x[:,0])
print(x[:,1])

tensor([1, 3])
tensor([2, 4])


In [109]:
print(x[0,:])
print(x[1,:])

tensor([1, 2])
tensor([3, 4])
